# Generated by Django 5.0.4 on 2024-04-08 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_bill_is_paid_alter_bill_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_items', to='billing.bill'),
        ),
    ]
